name: Linguist

on: push

jobs:
  linguist:
    name: Run linguist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/linguist-action@v1.0.0
        id: linguist
        with:
          path: './'
          percentage: true
      - name: Print linguist result
        run: echo "${{ steps.linguist.outputs.data }}"
      - name: creating readme
        run: |
            $myfile = fopen("README.md", "w")
            fwrite($myfile, "${{ steps.linguist.outputs.data }}")
            git commit README.md -m 'Re-build README.md'
            git push origin
